### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by JeroenHensmans** [MSPFE2019/Office365ProvisioningApp#1]
I'm getting 10 missing dependencies when trying to import the solution, all cloud flows it seems. 

- new_Approvals
- new_sharedazuread_3ef41
- new_sharedoffice365_7ba5e
- ....
-

**Comment by MSPFE2019** [comment]
@JeroenHensmans thank you for reporting this. I will address this as soon as possible.

**Comment by MSPFE2019** [comment]
@JeroenHensmans here is the updated version  - https://github.com/MSPFE2019/Office365ProvisioningApp/blob/main/Office365ProvisioningApp_1_0_0_8.zip

**Comment by JeroenHensmans** [comment]
Works great, cheers!

**Comment by MSPFE2019** [comment]
@JeroenHensmans I found another issue with the check__url flow, please download and update the solution. 

This is the newest solution : https://github.com/MSPFE2019/Office365ProvisioningApp/blob/main/Office365ProvisioningApp_1_0_0_9.zip
